config/routes.rb
Rails.application.routes.draw do
  root "home#welcome"

  get '/books', to: "books#index", as: :books
  get '/book/:id', to: "books#show", as: :book
  get '/books/new', to: "books#new", as: :new_book
  post '/books', to: "books#create"
  get '/books/:book_id/reviews', to: "reviews#index", as: :book_reviews
  get '/books/:book_id/reviews/new', to: "reviews#new", as: :new_book_review
  post '/books/:book_id/reviews', to: "reviews#create"



  delete '/books/:id', to: "books#delete", as: :delete_book
  delete '/authors/:id', to: "authors#delete", as: :delete_author
  delete '/:review_id', to: "reviews#delete", as: :delete_review
  get '/authors/:id', to: "authors#show", as: :author
  get '/:username', to: "reviews#index", as: :user_show
  get '/:username/:sort', to: "reviews#index", as: :user_show_sort
  get '/books/:sort/:order', to: "books#index", as: :books_sort
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :author_books, dependent: :destroy
  has_many :books, through: :author_books

  validates_uniqueness_of :name
end

app/models/author_book.rb
class AuthorBook < ApplicationRecord
  belongs_to :book 
  belongs_to :author
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :author_books, dependent: :destroy
  has_many :authors, through: :author_books
  has_many :reviews, dependent: :destroy

  validates_presence_of :pages, :pub_date
  validates_uniqueness_of :title

  def co_authors(author)
    authors.where.not(id: author.id)
  end

  def top_review
    sorted_reviews(:desc, 1).first
  end

  def sorted_reviews(order, limit)
    reviews.order(rating: order).limit(limit)
  end

  def average_rating
    reviews.average(:rating) || 0
  end

  def total_reviews
    reviews.count
  end

  def self.top_three
    Book.select("books.*, avg(rating) AS avg_rating")
    .joins(:reviews)
    .group(:id)
    .order("avg_rating DESC")
    .limit(3)
  end

  def self.bottom_three
    Book.select("books.*, avg(rating) AS avg_rating")
    .joins(:reviews)
    .group(:id)
    .order("avg_rating ASC")
    .limit(3)
  end

  def self.sort_by_pages(order)
    order(pages: order)
  end

  def self.sort_by_pub_date(order)
    order(pub_date: order)
  end

  def self.sort_by_num_reviews(order)
    joins(:reviews)
    .select("books.*, count(reviews) as num_reviews")
    .group(:id)
    .order("num_reviews #{order}")
  end
end

app/models/contributor.rb
class Contributor < ApplicationRecord
  validates_presence_of :name, :github
end

app/models/review.rb
  class Review < ApplicationRecord
    validates_presence_of :title, :rating, :content, :user_name

    belongs_to :book

    def self.sort_username(username)
      where(user_name: username)
    end

    def self.reviews_by_name(username)
      where(user_name: username).count
    end

    def self.sort_age(username, order)
      Review.where(user_name: username).order(created_at: order)
    end

    def self.most_reviews(limit)
      select("reviews.user_name, count(reviews.id) AS review_count")
      .group(:user_name)
      .order("review_count DESC")
      .limit(limit)
    end

    def self.still_exists(user)
      if Review.where(user_name: user).count > 0
        true
      else
        false
      end
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def show
    @author = Author.find(params[:id])
  end

  def delete
    author = Author.find(params[:id])
    author.books.each { |book| book.destroy }
    author.destroy
    redirect_to books_path
  end 
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = sort_params
    @top_three = Book.top_three
    @bottom_three = Book.bottom_three
    @most_reviews = Review.most_reviews(3)
  end

  def show
    @book = Book.find(params[:id])
    @average_rating = @book.average_rating
    @top_reviews = @book.sorted_reviews(:desc, 3)
    @bottom_reviews = @book.sorted_reviews(:asc, 3)
  end

  def new
    @book = Book.new
  end

  def create
    @error = "error"
    @book = Book.create(book_params)
    @book.title = @book.title.titleize
    authors = author_params[:authors].split(", ")


    if @book.save
      if authors.length == 0
        @book.destroy
        redirect_to new_book_path
        flash[:failure] = "A book needs at least one author"
      else
        authors.each do |author|
          book_author = Author.find_or_create_by(name: author.titleize)
          AuthorBook.create(author: book_author, book: @book)
        end
        redirect_to book_path(@book)
      end
    else
      render 'books/new'
    end
  end

  def delete
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :pages, :pub_date)
  end

  def author_params
    params.require(:book).permit(:authors)
  end

  def sort_params
    if params[:sort] == "pages"
      Book.sort_by_pages(params[:order].to_sym)
    elsif params[:sort] == "pub_date"
      Book.sort_by_pub_date(params[:order].to_sym)
    elsif params[:sort] == "reviews"
      Book.sort_by_num_reviews(params[:order].upcase)
    else
      Book.all
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def welcome
    @contributors = Contributor.all
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @user = params[:username]
    @reviews = show_params(@user)
  end

  def new
    @book = Book.find(params[:book_id])
    @review = Review.new(book: @book)
  end

  def create
    @book = Book.find(params[:book_id])
    review = @book.reviews.create(review_params)
    review.user_name = review.user_name.titleize
    if review.save
      redirect_to (book_path(@book))
    else
      @review = Review.new
      flash[:failure] = "All fields are required"
      render :new
    end
  end

  def delete
    review = Review.find(params[:review_id])
    user = review.user_name
    review.destroy
    if Review.still_exists(user)
      redirect_to(user_show_path(user))
    else
      redirect_to books_path
    end
  end

  private

  def review_params
    params.require(:review).permit(:title, :rating, :content, :user_name)
  end

  def show_params(user)
    if params[:sort]
      Review.sort_age(user, params[:sort].to_sym)
    else
      Review.sort_username(user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_error_message.html.erb
<% if object.errors.any? %>
  <div id=“error_message”>
      <%= pluralize(object.errors.count, @error) %> prevented
      it from being saved:
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
 <% end %>

app/views/authors/show.html.erb
<section class="author-show">
<section id="author-info"><br>
  <h1><%= @author.name %></h1><br>
</section>

  <p><%= link_to "Delete this author", delete_author_path(@author), method: :delete, data: { confirm: "Are you sure?" } %></p><br>


<% @author.books.each do |book| %>
  <section id="abook-<%= book.id %>">
    <h3 id="title"><%= link_to book.title, book_path(book) %></h3><br>
    <p>Pages: <%= book.pages %></p>
    <p>Publication Year: <%= book.pub_date %></p>
    <% if book.co_authors(@author).count > 0 %>
      <p>Co-Authors: <% book.co_authors(@author).each do |author| %><%= author.name %>
                    <% end %>
      </p><br><br>
    <% end %>

    <% unless book.reviews.count == 0 %>
      <section id="top-review">
        <p>Top Review: <%= book.top_review.title %></p>
        <p>Rating: <%= book.top_review.rating %></p>
        <p><%= link_to book.top_review.user_name, user_show_path(book.top_review.user_name)%> says: <%= book.top_review.content %></p><br><br>
      </section>
    <% end %>
  </section>
<% end %>
</section>

app/views/books/index.html.erb
<section class="book-index-header"><br><br>
  <h1 class="club-selection">Our Club Selection</h1>

  <section class="new_book">
      <%= link_to "Add a new book", new_book_path %>
  </section><br>
</section>

<section class="stats" id="book_stats">
  <section id="best_three">
    <h4>Highest-Rated Books:</h4><br>
      <ul>
        <% @top_three.each do |book| %>
          <li><%= link_to book.title, book_path(book) %>, Rating: <%= book.average_rating %></li>
        <% end %>
      </ul>
  </section>

  <section id="worst_three">
    <h4>Worst-Rated Books:</h4><br>
      <ul>
        <% @bottom_three.each do |book| %>
          <li><%= link_to book.title, book_path(book) %>, Rating: <%= book.average_rating %></li>
        <% end %>
      </ul>
  </section>

  <section id="most_reviews">
    <h4>Users With The Most Reviews:</h4><br>
    <ul>
      <% @most_reviews.each do |user| %>
        <li><%= link_to user.user_name, user_show_path(user.user_name) %>
        has written <%= Review.reviews_by_name(user.user_name) %> reviews</li>
      <% end %>
    </ul>
  </section>
</section>

<div class="books", id="books">
<ul>
  <% @books.each do |book| %>
    <li class="book" id="book-<%= book.id %>">
      <div class="book-info">
        <img class="book_cover" src="<%= book.book_cover_photo %>" alt="<%= book.book_cover_photo %>" alt="Book Cover Photo" width="200">
      </div>
      <div class="book-info">
        <ul>
          <li><%= link_to book.title, book_path(book) %></li>
          <li>Author(s):
          <% book.authors.each do |author| %><%= link_to author.name, author_path(author) %></li>
          <% end %>
          <li>Pages: <%= book.pages %></li>
          <li>Publication Year: <%= book.pub_date %></li>
          <li>Average Rating: <%= book.average_rating.round(1) %></li>
          <li>Total No. of Reviews: <%= book.total_reviews %></li>
        </ul>
      </div>
    </li>
  <% end %>
</ul>
</div>

app/views/books/new.html.erb
<section class="add-book"><br>
<h3>ADD A BOOK</h3><br>
<%= form_for @book do |f| %>
  <%= render :partial => "error_message", locals: {object: @book} %><br>
  <p>
    <%= f.label :title, "Title" %>
    <%= f.text_field :title %>
  </p><br>
  <p>
    <%= f.label :authors, "Author(s)" %>
    <%= f.text_field :authors, value: "" %>
  </p>
  <p><br>
    <%= f.label :pages, "Pages" %>
    <%= f.number_field :pages, min: 1 %><br>
  </p>
  <p><br>
    <%= f.label :pub_date, "Publication Date" %>
    <%= f.number_field :pub_date, min: 1455 %>
  </p>
  <p><br>
    <%= f.submit %>
  </p>
<% end %>

app/views/books/show.html.erb
<section class="book-show">
<section class="book" id="book-<%= @book.id %>"><br>
  <h1 class="book-title"><%= @book.title %></h1><br>

  <img src="<%= @book.book_cover_photo %>" alt="Book Cover Photo", width="200">
  <ul>
  <li>Author(s):
    <% @book.authors.each do |author| %>
      <%= link_to author.name, author_path(author) %></li>
    <% end %>
  <li>Pages: <%= @book.pages %></li>
  <li>Publication Year: <%= @book.pub_date %></li><br><br>
  </ul>
  <p><%= link_to "Delete this book", delete_book_path(@book), method: :delete, data: { confirm: "Are you sure?" }%></p><br>
  <p><%= link_to "Write a new review for this book", new_book_review_path(@book) %></p><br><br>
</section>

<% unless @book.reviews.empty? %>
    <p class="book">Average Rating: <%= @average_rating.round(1) %></p><br>
  <% end %>
<section class="review_stats" id="review_stats">
    <ul>
      <p>Top 3 Reviews:</p><br>
      <% @top_reviews.each do |review| %>
        <li><%= review.title %></li>
        <li>Rating: <%= review.rating %></li>
        <li>User: <%= review.user_name %></li><br>
      <% end %>
    </ul><br>
     <ul>
      <p>Bottom 3 Reviews:</p><br>
      <% @bottom_reviews.each do |review| %>
        <li><%= review.title %></li>
        <li>Rating: <%= review.rating %></li>
        <li>User: <%= review.user_name %></li><br>
      <% end %>
    </ul>
</section><br>

<h3 class="book">All Reviews</h3><br>
<section class="book-reviews">
  <% @book.reviews.each do |review| %>
    <section class="reviews" id="review-<%= review.id %>">
      <p>User: <%= link_to review.user_name, user_show_path(review.user_name) %></p>
      <p>Title: <%= review.title %></p>
      <p>Review: <%= review.content %></p>
      <p>Rating: <%= review.rating %></p><br>
    </section>
  <% end %>
</section>
</section>

app/views/home/welcome.html.erb
<section class="welcome"><br><br>
<h1>Welcome to our Book Club Project!</h1><br><br>

<h2>Project Contributors:</h2><br>

<% @contributors.each do |c| %>
  <section id="contributor-<%= c.id %>">
    <p>Name: <%= c.name %></p>
    <p>Github: <%= link_to c.github, "#{c.github}" %></p><br>
  </section>
<% end %>
</section>
<section class="welcome-image">
  <%= image_tag ("https://www.rd.com/wp-content/uploads/2017/11/How-Much-Does-a-Book-Need-to-Sell-to-Be-a-Bestseller-509582812-Billion-Photos-1024x683.jpg")%>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookClub</title>
    <%= csrf_meta_tags %>

    <link rel="application" href="reset.css">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <section id="nav-bar">
      <% flash.each do |type, message| %>
      <%= content_tag :div, message, class: type %>
      <%  end %>
      
      <% unless @contributors %>
        <div class="links" id ="homepage-link">
        <%= link_to "Return to Homepage", root_path %>
        </div>
      <% end %>
      <% if @books %>
        <section class="dropdown-nav">
          <div class="dropdown", id="dropdown">
            <button class="drop-button"> Sort Books 
              <i class="fa fa-caret-down"></i>
            </button>
          <div class="dropdown-content">
            <%= link_to "Page Count: Low to High", books_sort_path("pages", :asc) %>
            <%= link_to "Page Count: High to Low", books_sort_path("pages", :desc) %>
            <%= link_to "Publication Date: Oldest to Newest", books_sort_path("pub_date", :asc) %>
            <%= link_to "Publication Date: Newest to Oldest", books_sort_path("pub_date", :desc) %>
            <%= link_to "Most Reviewed", books_sort_path("reviews", :desc) %>
            <%= link_to "Least Reviewed", books_sort_path("reviews", :asc) %>
            </div>
          </div>
        </section>  
      <% end %>
      <% unless @books %>
        <%= link_to "Go to Books", books_path %>
      <% end %>
    </section>
    <%= yield %>
  </body>
</html>

app/views/reviews/index.html.erb
<section class="user-show"><br>
<h1><%= @user %>'s page</h1><br>

<section id="sorting">
  <%= link_to "Sort by oldest", user_show_sort_path(@user, :asc)%><br>
  <%= link_to "Sort by newest", user_show_sort_path(@user, :desc)%>
</section><br>

<ul id="reviews">
  <% @reviews.each do |review| %>
    <li class="review" id="review-<%= review.id %>">
      <h2><%= link_to review.book.title, book_path(review.book) %></h2>
      <h3><%= review.title %></h3>
      <p>Rating: <%= review.rating %></p>
      <p><%= review.content %></p>
      <p><%= link_to "Delete this review", delete_review_path(review), method: :delete, data: { confirm: "Are you sure?" } %></p><br>
<% end %>
</ul>
</section>

app/views/reviews/new.html.erb
<section class="add-review"><br>
<h3>ADD A REVIEW</h3><br>
<%= form_for [@book, @review] do |f| %>
  <%= render :partial => "error_message", locals: {object: @review} %>
  <p>
    <%= f.label :title, "Review Title"%>
    <%= f.text_field :title %>
  </p><br>
  <p>
    <%= f.label :rating %>
    <%= f.number_field :rating, min: 1, max: 5 %>
  </p><br>
  <p>
    <%= f.label :content, "Review" %>
    <%= f.text_area :content %>
  </p><br>
  <p>
    <%= f.label :user_name, "Username" %>
    <%= f.text_field :user_name %>
  </p><br>
  <p>
    <%= f.submit %>
<% end %>
</section>